version: "3.9"

networks:
  dev-network:
    driver: bridge

services:

  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always
    networks:
      - dev-network

  warehouse_api:
    container_name: warehouse_api
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    networks:
      - dev-network
    depends_on:
      - db
